# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f980590ccd1912873deac0f1dc052b2"
name = "usama-demo"
handle = "usama-demo"
application_url = "https://cookbook-guinea-speeds-worldcat.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://cookbook-guinea-speeds-worldcat.trycloudflare.com/auth/callback", "https://cookbook-guinea-speeds-worldcat.trycloudflare.com/auth/shopify/callback", "https://cookbook-guinea-speeds-worldcat.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
